
version: 2.1
orbs:
  node: circleci/node@5.0.0
<<<<<<< HEAD
  aws-cli: circleci/aws-cli@12
=======
  aws-cli: circleci/aws-cli@2
>>>>>>> 44d55fd8f09ccc6730039383fb7c5c379edba514
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
<<<<<<< HEAD
          node-version: '17.5.0'
      - checkout:
      - aws-cli/setup:
=======
          node-version: '117.5.0'
      - checkout
      - aws-cli/setup
>>>>>>> 44d55fd8f09ccc6730039383fb7c5c379edba514
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Test App
          command: |
            npm run frontend:test
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
