version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: cimg/node:17.5.0-browsers
    steps:
      - node/install:
          node-version: "17.5.0"
      - checkout
      - aws-cli/setup
      - run: 
          name: Install Chrome latest version
          command: |
            sudo apt-get update &&
            sudo apt-get install lsb-release libappindicator3-1 &&
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&
            sudo dpkg -i google-chrome.deb &&
            sudo sed -i 's|HERE/chrome"|HERE/chrome" --no-sandbox|g' /opt/google/chrome/google-chrome &&
            rm google-chrome.deb

      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Unit test
          command: |
            npm run frontend:test
      - run:
          name: E2E test
          command: |
            npm run frontend:e2e
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
