
version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - node/install:
          node-version: '17.5.0'
      - checkout
      - aws-cli/setup
      - browser-tools/install-chrome
      - run:
          name: Install webdriver-manager
          command: npm i -g webdriver-manager
      - run:
          name: Clean and update webdriver
          command: webdriver-manager clean && webdriver-manager update
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Unit test
          command: |
            npm run frontend:test
      - run:
          name: E2E test
          command: |
            npm run frontend:e2e
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
