
version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2
  browser-tools: circleci/browser-tools@1.2.4
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - node/install:
          node-version: '17.5.0'
      - checkout
      - aws-cli/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: 
          name: "Install webdriver"
          command: npm install -g webdriver-manager
      - run: 
          name: "Start webdriver"
          background: true
          command: npm run webdriver:start
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: E2E test
          command: |
            npm run frontend:e2e
      - run:
          name: Unit test
          command: |
            npm run frontend:test
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
